name: "mnist_classifier_pretrained"
model_type: FEED_FORWARD_NET
hyperparams {
  base_epsilon: 0.01
  epsilon_decay : NONE
  epsilon_decay_half_life : 5000
  initial_momentum : 0.5
  final_momentum : 0.9
  momentum_change_steps : 3000
  sparsity : true
  sparsity_target : 0.1
  sparsity_cost : 0.001
  sparsity_damping : 0.9
  dropout : true
  dropout_prob : 0.5
  apply_weight_norm : false
  weight_norm : 3
  apply_l2_decay: true
  l2_decay: 0.001
  activation: LOGISTIC
}

layer {
  name: "input_layer"
  dimensions: 784
  shape:28
  shape:28
  is_input: true
  param {
    name: "bias"
    initialization: CONSTANT
  }
  data_field {
    train: "train_full_data"
    test: "test_data"
  }
  hyperparams {
    dropout_prob: 0.2
    sparsity: false
  }
  loss_function: SQUARED_LOSS
  performance_stats {
    compute_error: true
  }
}
layer {
  name: "output_layer"
  dimensions: 1
  numlabels: 10
  param {
    name: "bias"
    initialization: CONSTANT
  }
  hyperparams{
    dropout: false
    activation: SOFTMAX
    enable_display: false
    apply_l2_decay: false
    sparsity: false
  }
  is_output: true
  loss_function: CROSS_ENTROPY
  data_field {
    train: "train_full_labels"
    #train: "train_labels"
    #validation: "validation_labels"
    test: "test_labels"
  }
  performance_stats {
    compute_cross_entropy: true
    compute_correct_preds: true
  }
}


layer {
  name: "hidden1"
  dimensions: 1024
  shape: 32
  shape: 32
  param {
    name: "bias"
    initialization: PRETRAINED
    pretrained_model: "/ais/gobi3/u/nitish/mnist/models/mnist_rbm1_LAST"
  }
  hyperparams{
    apply_l2_decay: false
    sparsity_target: 0.1
  }
  performance_stats {
    compute_sparsity: true
  }
}
layer {
  name: "hidden2"
  dimensions: 1024
  shape: 32
  shape: 16
  param {
    name: "bias"
    initialization: PRETRAINED
    pretrained_model: "/ais/gobi3/u/nitish/mnist/models/mnist_dbn2_rbm_LAST"
  }
  hyperparams{
    apply_l2_decay: false
    sparsity_target: 0.1
  }
  performance_stats {
    compute_sparsity: true
  }
}
layer {
  name: "hidden3"
  dimensions: 2048
  shape: 32
  shape: 32
  param {
    name: "bias"
    initialization: PRETRAINED
    pretrained_model: "/ais/gobi3/u/nitish/mnist/models/mnist_dbn3_rbm_LAST"
  }
  hyperparams{
    apply_l2_decay: false
    sparsity_target: 0.05
  }
  performance_stats {
    compute_sparsity: true
  }
}

edge {
  node1: "input_layer"
  node2: "hidden1"
  receptive_field_width: 28
  display_rows: 32
  display_cols: 32
  param {
    name: "weight"
    initialization: PRETRAINED
    pretrained_model: "/ais/gobi3/u/nitish/mnist/models/mnist_rbm1_LAST"
  }
}
edge {
  node1: "hidden1"
  node2: "hidden2"
  param {
    name: "weight"
    initialization: PRETRAINED
    pretrained_model: "/ais/gobi3/u/nitish/mnist/models/mnist_dbn2_rbm_LAST"
  }
}

edge {
  node1: "hidden2"
  node2: "hidden3"
  param {
    name: "weight"
    initialization: PRETRAINED
    pretrained_model: "/ais/gobi3/u/nitish/mnist/models/mnist_dbn3_rbm_LAST"
  }
}

edge {
  node1: "hidden3"
  node2: "output_layer"
  param {
    name: "weight"
    initialization: DENSE_GAUSSIAN_SQRT_FAN_IN
    sigma: 1.0
  }
}
