optimizer : CD
stopcondition {
  all_processed: false
  steps: 100000
}
train: true 
batchsize: 100
data_proto: "/ais/gobi3/u/nitish/mnist/mnist.pbtxt"
eval_after: 1000
checkpoint_after: 10000
checkpoint_directory: "/ais/gobi3/u/nitish/mnist/models"
show_after: 1000
randomize: true
