optimizer : GRADIENT_DESCENT
stopcondition {
  all_processed: false
  steps: 1000000
}
train: true 
batchsize: 100
data_proto: "/ais/gobi3/u/nitish/mnist/mnist.pbtxt"
eval_after: 1000
checkpoint_after: 100000
checkpoint_directory: "/ais/gobi3/u/nitish/mnist/models"
show_after: 0
randomize: true
