optimizer: CD
stopcondition {
  all_processed: false
  steps: 100000
}
train: true
batchsize: 128
data_proto: "flickr.pbtxt"
eval_after: 5000
checkpoint_after: 50000
checkpoint_directory: "/ais/gobi3/u/nitish/flickr/dbn_models"
randomize: true
verbose: false
data_proto_prefix: "/ais/gobi3/u/nitish/flickr"
